# Generated by Django 4.2.30 on 2026-04-23 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain letters, numbers, spaces and @/./+/-/_', regex='^[\\w\\s.@+-]+$')]),
        ),
    ]
